name: upload docs
on: workflow_dispatch
jobs:
  upload_docs:
    runs-on: ubuntu-latest
    steps:
      - name: gen docs
        id: docs
        uses: nugentcaillin/actions/doxygen-gen@main
      - name: request docs page update
        uses: peter-evans/repository-dispatch@v4
        with:
          token: ${{ secrets.PAT }}
          repository: nugentcaillin/homelab-orchestration
          event-type: docs-update
          client-payload: '{"artifact-id": "${{ steps.docs.outputs.artifact-id }}", "folder": "othello"}'
