name: upload docs
on: workflow_dispatch
jobs:
  upload_docs:
    runs-on: ubuntu-latest
    steps:
      - name: gen docs
        id: docs
        uses: nugentcaillin/actions/doxygen-gen@main
      - name: echo ID
        run: echo "ARTIFACT ID: ${{docs.artifact-id}}"
